<?php
require_once('libs/tcpdf.php'); // Load TCPDF
session_start();

// Database Connection
$conn = new mysqli("localhost", "root", "", "mailfor");
if ($conn->connect_error) {
    die("Database connection failed: " . $conn->connect_error);
}

// Validate ID
if (!isset($_GET['id']) || !is_numeric($_GET['id'])) {
    die("Invalid request!");
}

$id = intval($_GET['id']);

// Get current user and website
$user_id = $_SESSION['user_id'] ?? 1;
$website_id = $_SESSION['website_id'] ?? 1;

// Fetch Record from Database (securely filtered by user_id & website_id)
$sql = "SELECT * FROM logs WHERE id = ? AND user_id = ? AND website_id = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("iii", $id, $user_id, $website_id);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("No record found or access denied!");
}

$data = $result->fetch_assoc();
$stmt->close();
$conn->close();

// Fetch Whois Data safely
$whoisIp = !empty($data['webrtc_ip']) ? $data['webrtc_ip'] : $data['ip'];
$whoisUrl = "https://rdap.org/ip/" . urlencode($whoisIp);
$whoisData = @file_get_contents($whoisUrl);
$whoisJson = $whoisData ? json_decode($whoisData, true) : [];

$country = $whoisJson["country"] ?? "N/A";
$handle = $whoisJson["handle"] ?? "N/A";
$events = isset($whoisJson["events"]) ? implode(", ", array_column($whoisJson["events"], "eventAction")) : "N/A";

$emails = [];
$phones = [];
$addresses = [];

if (!empty($whoisJson["entities"])) {
    foreach ($whoisJson["entities"] as $entity) {
        if (!empty($entity["vcardArray"][1])) {
            foreach ($entity["vcardArray"][1] as $vcard) {
                if ($vcard[0] === "email") {
                    $emails[] = htmlspecialchars($vcard[3]);
                } elseif ($vcard[0] === "tel") {
                    $phones[] = htmlspecialchars($vcard[3]);
                } elseif ($vcard[0] === "adr") {
                    $addresses[] = htmlspecialchars(implode(", ", array_filter($vcard[3])));
                }
            }
        }
    }
}

// Fetch Location Data safely
$locationUrl = "http://ip-api.com/json/" . urlencode($whoisIp);
$locationData = @file_get_contents($locationUrl);
$locationJson = $locationData ? json_decode($locationData, true) : [];

$locCountry = $locationJson["country"] ?? "N/A";
$region = $locationJson["regionName"] ?? "N/A";
$city = $locationJson["city"] ?? "N/A";
$isp = $locationJson["isp"] ?? "N/A";
$latitude = $locationJson["lat"] ?? "N/A";
$longitude = $locationJson["lon"] ?? "N/A";

// Create PDF
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor("VPN Detection System");
$pdf->SetTitle("IP Report - " . $data['ip']);
$pdf->SetHeaderData('', 0, "IP Report: " . $data['ip'], "Generated by VPN Detection System");
$pdf->setHeaderFont([PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN]);
$pdf->setFooterFont([PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA]);
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 12);

// Generate Report
$html = "<h2>IP Report for " . htmlspecialchars($data['ip']) . "</h2>

<h3>Database Information</h3>
<ul>
    <li><strong>ID:</strong> {$data['id']}</li>
    <li><strong>IP Route:</strong> {$data['ip']}</li>
    <li><strong>Reverse DNS:</strong> {$data['reverse_dns']}</li>
    <li><strong>Real IP:</strong> {$data['real_ip']}</li>
    <li><strong>VPN Detected:</strong> " . ($data['is_vpn'] ? '✅ Yes' : '✕ No') . "</li>
    <li><strong>Tor Usage:</strong> " . ($data['is_tor'] ? '✅ Yes' : '✕ No') . "</li>
    <li><strong>WebRTC IP:</strong> {$data['webrtc_ip']}</li>
    <li><strong>DNS Leak IP:</strong> {$data['dns_leak_ip']}</li>
    <li><strong>User Agent:</strong> {$data['user_agent']}</li>
    <li><strong>Screen Resolution:</strong> {$data['screen_resolution']}</li>
    <li><strong>Language:</strong> {$data['language']}</li>
    <li><strong>Timezone:</strong> {$data['timezone']}</li>
    <li><strong>Cookies Enabled:</strong> {$data['cookies_enabled']}</li>
    <li><strong>Referrer:</strong> {$data['referrer']}</li>
    <li><strong>Plugins:</strong> {$data['plugins']}</li>
    <li><strong>CPU:</strong> {$data['cpu_cores']}</li>
    <li><strong>RAM:</strong> {$data['ram']}</li>
    <li><strong>GPU:</strong> {$data['gpu']}</li>
    <li><strong>Battery:</strong> {$data['battery']}</li>
    <li><strong>Timestamp:</strong> {$data['timestamp']}</li>
</ul>

<h3>Whois Information</h3>
<ul>
    <li><strong>Country:</strong> $country</li>
    <li><strong>Handle:</strong> $handle</li>
    <li><strong>Events:</strong> $events</li>
    <li><strong>Email(s):</strong> " . (!empty($emails) ? implode(", ", $emails) : "N/A") . "</li>
    <li><strong>Phone(s):</strong> " . (!empty($phones) ? implode(", ", $phones) : "N/A") . "</li>
    <li><strong>Address(es):</strong> " . (!empty($addresses) ? implode(", ", $addresses) : "N/A") . "</li>
</ul>

<h3>Location Information</h3>
<ul>
    <li><strong>Country:</strong> $locCountry</li>
    <li><strong>Region:</strong> $region</li>
    <li><strong>City:</strong> $city</li>
    <li><strong>ISP:</strong> $isp</li>
    <li><strong>Latitude:</strong> $latitude</li>
    <li><strong>Longitude:</strong> $longitude</li>
</ul>
";

$pdf->writeHTML($html, true, false, true, false, '');

// Raw JSON Pages
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 8);
$whoisJsonFormatted = htmlspecialchars(json_encode($whoisJson, JSON_PRETTY_PRINT));
$pdf->writeHTML("<h3>Whois JSON Data</h3><pre>$whoisJsonFormatted</pre>", true, false, true, false, '');

$pdf->AddPage();
$pdf->SetFont('helvetica', '', 8);
$locationJsonFormatted = htmlspecialchars(json_encode($locationJson, JSON_PRETTY_PRINT));
$pdf->writeHTML("<h3>Location JSON Data</h3><pre>$locationJsonFormatted</pre>", true, false, true, false, '');

// Output PDF
$pdf->Output("IP_Report_" . htmlspecialchars($data['ip']) . ".pdf", 'D');
?>
